nickjwilde/urls.py
from django.conf.urls import url

from . import views

app_name = 'nickjwilde'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('nickjwilde.urls')),
    url(r'^admin/', admin.site.urls),
]

nickjwilde/models.py
from django.db import models

# Create your models here.
class Skill(models.Model):
    num_years = models.IntegerField()
    image_name = models.CharField(max_length=255)

    def num_years_text(self):
        return "".join(str(self.num_years) + ' years' if self.num_years > 1 else str(self.num_years) + ' year')

    def __str__(self):
        return self.image_name.split('.')[0]

nickjwilde/forms.py
from django import forms

class ContactForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=50, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(label='Last Name', max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'placeholder': 'somebody@you.com'}))

nickjwilde/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .models import Skill
from .forms import ContactForm

# Create your views here.
def home(request):
    return render(request, 'nickjwilde/home.html', None)

def about(request):
    skills = Skill.objects.all().order_by('-num_years')
    context = {'skills': skills}
    return render(request, 'nickjwilde/about.html', context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, label_suffix='')

        if form.is_valid():
            return HttpResponseRedirect('/thanks/')
    else:
        form = ContactForm(label_suffix='')
    return render(request, 'nickjwilde/contact.html', {'form': form})

nickjwilde/templates/nickjwilde/about.html
{% extends "nickjwilde/base.html" %}

{% load static %}
{% block head %}
    <title>About</title>
{% endblock %}

{% block body %}
    <h1>About Me</h1>
    <p>I'm a Software Developer.</p>
    <h2>Skills</h2>
    <div class="skill-list">
    {% for skill in skills %}
        <div class="skill">
            <img src="static/nickjwilde/img/{{ skill.image_name}}" />
            <div class="overlay">
                <div class="years">{{ skill.num_years_text}}</div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

nickjwilde/templates/nickjwilde/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

	<link href={% static "nickjwilde/css/style.css" %} type="text/css" rel="stylesheet" />
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block nav %}
	<div class="nw-navbar">
		<a class="nw-navbar-item nw-button nw-hide-medium nw-hide-large nw-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
			<i class="fa fa-bars"></i>
		</a>
		<a href="#">about</a>
		<a href="#">posts</a>
		<a href="#">contact</a>
	</div>
    {% endblock %}

    <div class="nw-content">
        {% block body %}
        {% endblock %}
    </div>
    
    <div class="nw-footer">
        {% block footer %}
        {% endblock %}
        <p>&copy; 2017 Nick Wilde</p>
    </div>
    <script src="{% static 'nickjwilde/js/main.js' %}" type="text/javascript"></script>

</body>
</html>

nickjwilde/templates/nickjwilde/contact.html
{% extends 'nickjwilde/base.html' %}
{% block body %}
    <h1>Contact</h1>
    <form action="/contact/" id="contactForm" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

nickjwilde/templates/nickjwilde/home.html
{% extends "nickjwilde/base.html" %}
{% block head %}
    <title>Home</title>
{% endblock %}

{% block body %}
    <h1>
        <span class="uline-h">Hello World</span>
    </h1>
    <p>Welcome to my personal website. I built this website to learn more about HTML, CSS, Javascript/jQuery and Python/Django. I love to learn new things, and you can always see the things I've learned on the <a style="text-decoration: none" href="#">Posts</a> page. If you'd like to know the skills I've acquired while programming, checkout the <a style="text-decoration: none" href="{% url 'nickjwilde:about' %}">About</a> page. If you'd like to get in touch with me, use the <a style="text-decoration: none" href="{% url 'nickjwilde:contact' %}">Contact</a> page.</p>
{% endblock %}